# Data Cleaning and Preprocessing

In [54]:
# import inportant libraries 
# import data
import pandas as pd

df = pd.read_csv('MachineLearningRating_v3.txt', delimiter='|')  # Adjust delimiter if needed
print(df.head())  # Preview first few rows of the data

C:\Users\user\AppData\Local\Temp\ipykernel_25592\3238008079.py:5: DtypeWarning: Columns (32,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('MachineLearningRating_v3.txt', delimiter='|')  # Adjust delimiter if needed

   UnderwrittenCoverID  PolicyID     TransactionMonth  IsVATRegistered  \
0               145249     12827  2015-03-01 00:00:00             True
1               145249     12827  2015-05-01 00:00:00             True
2               145249     12827  2015-07-01 00:00:00             True
3               145255     12827  2015-05-01 00:00:00             True
4               145255     12827  2015-07-01 00:00:00             True

  Citizenship          LegalType Title Language                 Bank  \
0              Close Corporation    Mr  English  First National Bank
1              Close Corporation    Mr  English  First National Bank
2              Close Corporation    Mr  English  First National Bank
3              Close Corporation    Mr  English  First National Bank
4              Close Corporation    Mr  English  First National Bank

       AccountType  ...                    ExcessSelected CoverCategory  \
0  Current account  ...             Mobility - Windscreen    Windscreen
1  Current account  ...             Mobility - Windscreen    Windscreen
2  Current account  ...             Mobility - Windscreen    Windscreen
3  Current account  ...  Mobility - Metered Taxis - R2000    Own damage
4  Current account  ...  Mobility - Metered Taxis - R2000    Own damage

    CoverType            CoverGroup              Section  \
0  Windscreen  Comprehensive - Taxi  Motor Comprehensive
1  Windscreen  Comprehensive - Taxi  Motor Comprehensive
2  Windscreen  Comprehensive - Taxi  Motor Comprehensive
3  Own Damage  Comprehensive - Taxi  Motor Comprehensive
4  Own Damage  Comprehensive - Taxi  Motor Comprehensive

                           Product StatutoryClass StatutoryRiskType  \
0  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
1  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
2  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
3  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
4  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant

   TotalPremium TotalClaims
0     21.929825         0.0
1     21.929825         0.0
2      0.000000         0.0
3    512.848070         0.0
4      0.000000         0.0

[5 rows x 52 columns]

In [55]:
# Specify the dtype for problematic columns, e.g., treating them as 'str' (string)
dtype_spec = {32: str, 37: str}
df = pd.read_csv('MachineLearningRating_v3.txt', delimiter='|', dtype=dtype_spec)

In [56]:
print(df.head())

   UnderwrittenCoverID  PolicyID     TransactionMonth  IsVATRegistered  \
0               145249     12827  2015-03-01 00:00:00             True
1               145249     12827  2015-05-01 00:00:00             True
2               145249     12827  2015-07-01 00:00:00             True
3               145255     12827  2015-05-01 00:00:00             True
4               145255     12827  2015-07-01 00:00:00             True

  Citizenship          LegalType Title Language                 Bank  \
0              Close Corporation    Mr  English  First National Bank
1              Close Corporation    Mr  English  First National Bank
2              Close Corporation    Mr  English  First National Bank
3              Close Corporation    Mr  English  First National Bank
4              Close Corporation    Mr  English  First National Bank

       AccountType  ...                    ExcessSelected CoverCategory  \
0  Current account  ...             Mobility - Windscreen    Windscreen
1  Current account  ...             Mobility - Windscreen    Windscreen
2  Current account  ...             Mobility - Windscreen    Windscreen
3  Current account  ...  Mobility - Metered Taxis - R2000    Own damage
4  Current account  ...  Mobility - Metered Taxis - R2000    Own damage

    CoverType            CoverGroup              Section  \
0  Windscreen  Comprehensive - Taxi  Motor Comprehensive
1  Windscreen  Comprehensive - Taxi  Motor Comprehensive
2  Windscreen  Comprehensive - Taxi  Motor Comprehensive
3  Own Damage  Comprehensive - Taxi  Motor Comprehensive
4  Own Damage  Comprehensive - Taxi  Motor Comprehensive

                           Product StatutoryClass StatutoryRiskType  \
0  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
1  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
2  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
3  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
4  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant

   TotalPremium TotalClaims
0     21.929825         0.0
1     21.929825         0.0
2      0.000000         0.0
3    512.848070         0.0
4      0.000000         0.0

[5 rows x 52 columns]

# Data Understanding

In [8]:
# understand the datatypes of each column
print(df.dtypes)

UnderwrittenCoverID           int64
PolicyID                      int64
TransactionMonth             object
IsVATRegistered                bool
Citizenship                  object
LegalType                    object
Title                        object
Language                     object
Bank                         object
AccountType                  object
MaritalStatus                object
Gender                       object
Country                      object
Province                     object
PostalCode                    int64
MainCrestaZone               object
SubCrestaZone                object
ItemType                     object
mmcode                      float64
VehicleType                  object
RegistrationYear              int64
make                         object
Model                        object
Cylinders                   float64
cubiccapacity               float64
kilowatts                   float64
bodytype                     object
NumberOfDoors               float64
VehicleIntroDate             object
CustomValueEstimate         float64
AlarmImmobiliser             object
TrackingDevice               object
CapitalOutstanding           object
NewVehicle                   object
WrittenOff                   object
Rebuilt                      object
Converted                    object
CrossBorder                  object
NumberOfVehiclesInFleet     float64
SumInsured                  float64
TermFrequency                object
CalculatedPremiumPerTerm    float64
ExcessSelected               object
CoverCategory                object
CoverType                    object
CoverGroup                   object
Section                      object
Product                      object
StatutoryClass               object
StatutoryRiskType            object
TotalPremium                float64
TotalClaims                 float64
dtype: object

In [57]:
# List of correct column names
column_names = [
    'UnderwrittenCoverID', 'PolicyID', 'TransactionMonth', 'IsVATRegistered', 'Citizenship', 
    'LegalType', 'Title', 'Language', 'Bank', 'AccountType', 'MaritalStatus', 'Gender', 
    'Country', 'Province', 'PostalCode', 'MainCrestaZone', 'SubCrestaZone', 'ItemType', 
    'mmcode', 'VehicleType', 'RegistrationYear', 'make', 'Model', 'Cylinders', 'cubiccapacity', 
    'kilowatts', 'bodytype', 'NumberOfDoors', 'VehicleIntroDate', 'CustomValueEstimate', 
    'AlarmImmobiliser', 'TrackingDevice', 'CapitalOutstanding', 'NewVehicle', 'WrittenOff', 
    'Rebuilt', 'Converted', 'CrossBorder', 'NumberOfVehiclesInFleet', 'SumInsured', 
    'TermFrequency', 'CalculatedPremiumPerTerm', 'ExcessSelected', 'CoverCategory', 'CoverType', 
    'CoverGroup', 'Section', 'Product', 'StatutoryClass', 'StatutoryRiskType', 'TotalPremium', 
    'TotalClaims'
]

# Assign the column names to your DataFrame
df.columns = column_names

# Display the first few rows of the DataFrame to check if everything is correct
print(df.head())

   UnderwrittenCoverID  PolicyID     TransactionMonth  IsVATRegistered  \
0               145249     12827  2015-03-01 00:00:00             True
1               145249     12827  2015-05-01 00:00:00             True
2               145249     12827  2015-07-01 00:00:00             True
3               145255     12827  2015-05-01 00:00:00             True
4               145255     12827  2015-07-01 00:00:00             True

  Citizenship          LegalType Title Language                 Bank  \
0              Close Corporation    Mr  English  First National Bank
1              Close Corporation    Mr  English  First National Bank
2              Close Corporation    Mr  English  First National Bank
3              Close Corporation    Mr  English  First National Bank
4              Close Corporation    Mr  English  First National Bank

       AccountType  ...                    ExcessSelected CoverCategory  \
0  Current account  ...             Mobility - Windscreen    Windscreen
1  Current account  ...             Mobility - Windscreen    Windscreen
2  Current account  ...             Mobility - Windscreen    Windscreen
3  Current account  ...  Mobility - Metered Taxis - R2000    Own damage
4  Current account  ...  Mobility - Metered Taxis - R2000    Own damage

    CoverType            CoverGroup              Section  \
0  Windscreen  Comprehensive - Taxi  Motor Comprehensive
1  Windscreen  Comprehensive - Taxi  Motor Comprehensive
2  Windscreen  Comprehensive - Taxi  Motor Comprehensive
3  Own Damage  Comprehensive - Taxi  Motor Comprehensive
4  Own Damage  Comprehensive - Taxi  Motor Comprehensive

                           Product StatutoryClass StatutoryRiskType  \
0  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
1  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
2  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
3  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
4  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant

   TotalPremium TotalClaims
0     21.929825         0.0
1     21.929825         0.0
2      0.000000         0.0
3    512.848070         0.0
4      0.000000         0.0

[5 rows x 52 columns]

# Find Missing Values

In [10]:
print(df.isnull().sum())

UnderwrittenCoverID               0
PolicyID                          0
TransactionMonth                  0
IsVATRegistered                   0
Citizenship                       0
LegalType                         0
Title                             0
Language                          0
Bank                         145961
AccountType                   40232
MaritalStatus                  8259
Gender                         9536
Country                           0
Province                          0
PostalCode                        0
MainCrestaZone                    0
SubCrestaZone                     0
ItemType                          0
mmcode                          552
VehicleType                     552
RegistrationYear                  0
make                            552
Model                           552
Cylinders                       552
cubiccapacity                   552
kilowatts                       552
bodytype                        552
NumberOfDoors                   552
VehicleIntroDate                552
CustomValueEstimate          779642
AlarmImmobiliser                  0
TrackingDevice                    0
CapitalOutstanding                2
NewVehicle                   153295
WrittenOff                   641901
Rebuilt                      641901
Converted                    641901
CrossBorder                  999400
NumberOfVehiclesInFleet     1000098
SumInsured                        0
TermFrequency                     0
CalculatedPremiumPerTerm          0
ExcessSelected                    0
CoverCategory                     0
CoverType                         0
CoverGroup                        0
Section                           0
Product                           0
StatutoryClass                    0
StatutoryRiskType                 0
TotalPremium                      0
TotalClaims                       0
dtype: int64

In [11]:
print(df['Citizenship'].unique())  # Replace with any other categorical column

['  ' 'AF' 'ZA' 'ZW']

In [12]:
print(df.dtypes)

UnderwrittenCoverID           int64
PolicyID                      int64
TransactionMonth             object
IsVATRegistered                bool
Citizenship                  object
LegalType                    object
Title                        object
Language                     object
Bank                         object
AccountType                  object
MaritalStatus                object
Gender                       object
Country                      object
Province                     object
PostalCode                    int64
MainCrestaZone               object
SubCrestaZone                object
ItemType                     object
mmcode                      float64
VehicleType                  object
RegistrationYear              int64
make                         object
Model                        object
Cylinders                   float64
cubiccapacity               float64
kilowatts                   float64
bodytype                     object
NumberOfDoors               float64
VehicleIntroDate             object
CustomValueEstimate         float64
AlarmImmobiliser             object
TrackingDevice               object
CapitalOutstanding           object
NewVehicle                   object
WrittenOff                   object
Rebuilt                      object
Converted                    object
CrossBorder                  object
NumberOfVehiclesInFleet     float64
SumInsured                  float64
TermFrequency                object
CalculatedPremiumPerTerm    float64
ExcessSelected               object
CoverCategory                object
CoverType                    object
CoverGroup                   object
Section                      object
Product                      object
StatutoryClass               object
StatutoryRiskType            object
TotalPremium                float64
TotalClaims                 float64
dtype: object

In [13]:
#Convert columns with date-related information, such as TransactionMonth and VehicleIntroDate, to datetime
df['TransactionMonth'] = pd.to_datetime(df['TransactionMonth'])
df['VehicleIntroDate'] = pd.to_datetime(df['VehicleIntroDate'])

C:\Users\user\AppData\Local\Temp\ipykernel_25592\2408201849.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['VehicleIntroDate'] = pd.to_datetime(df['VehicleIntroDate'])

In [14]:
df['VehicleIntroDate'] = pd.to_datetime(df['VehicleIntroDate'], format='%Y-%m-%d')

In [15]:
print(df.dtypes)

UnderwrittenCoverID                  int64
PolicyID                             int64
TransactionMonth            datetime64[ns]
IsVATRegistered                       bool
Citizenship                         object
LegalType                           object
Title                               object
Language                            object
Bank                                object
AccountType                         object
MaritalStatus                       object
Gender                              object
Country                             object
Province                            object
PostalCode                           int64
MainCrestaZone                      object
SubCrestaZone                       object
ItemType                            object
mmcode                             float64
VehicleType                         object
RegistrationYear                     int64
make                                object
Model                               object
Cylinders                          float64
cubiccapacity                      float64
kilowatts                          float64
bodytype                            object
NumberOfDoors                      float64
VehicleIntroDate            datetime64[ns]
CustomValueEstimate                float64
AlarmImmobiliser                    object
TrackingDevice                      object
CapitalOutstanding                  object
NewVehicle                          object
WrittenOff                          object
Rebuilt                             object
Converted                           object
CrossBorder                         object
NumberOfVehiclesInFleet            float64
SumInsured                         float64
TermFrequency                       object
CalculatedPremiumPerTerm           float64
ExcessSelected                      object
CoverCategory                       object
CoverType                           object
CoverGroup                          object
Section                             object
Product                             object
StatutoryClass                      object
StatutoryRiskType                   object
TotalPremium                       float64
TotalClaims                        float64
dtype: object

In [16]:
df['VehicleIntroDate'] = pd.to_datetime(df['VehicleIntroDate'], format='%Y-%m-%d')

In [17]:
print(df['VehicleIntroDate'].dtype)
print(df['VehicleIntroDate'].head())

datetime64[ns]
0   2002-06-01
1   2002-06-01
2   2002-06-01
3   2002-06-01
4   2002-06-01
Name: VehicleIntroDate, dtype: datetime64[ns]

In [18]:
#For categorical data, you might consider converting columns to category type to optimize memory usage:
categorical_cols = ['Citizenship', 'LegalType', 'Title', 'Language', 'Bank', 'AccountType', 
                    'MaritalStatus', 'Gender', 'Country', 'Province', 'MainCrestaZone', 
                    'SubCrestaZone', 'ItemType', 'VehicleType', 'make', 'Model', 'bodytype',
                    'AlarmImmobiliser', 'TrackingDevice', 'CapitalOutstanding', 'NewVehicle',
                    'WrittenOff', 'Rebuilt', 'Converted', 'CrossBorder', 'TermFrequency', 
                    'ExcessSelected', 'CoverCategory', 'CoverType', 'CoverGroup', 'Section', 
                    'Product', 'StatutoryClass', 'StatutoryRiskType']

df[categorical_cols] = df[categorical_cols].astype('category')

In [19]:
# Ensure the boolean columns are correctly represented:
df['IsVATRegistered'] = df['IsVATRegistered'].astype(bool)

In [20]:
print(df.dtypes)

UnderwrittenCoverID                  int64
PolicyID                             int64
TransactionMonth            datetime64[ns]
IsVATRegistered                       bool
Citizenship                       category
LegalType                         category
Title                             category
Language                          category
Bank                              category
AccountType                       category
MaritalStatus                     category
Gender                            category
Country                           category
Province                          category
PostalCode                           int64
MainCrestaZone                    category
SubCrestaZone                     category
ItemType                          category
mmcode                             float64
VehicleType                       category
RegistrationYear                     int64
make                              category
Model                             category
Cylinders                          float64
cubiccapacity                      float64
kilowatts                          float64
bodytype                          category
NumberOfDoors                      float64
VehicleIntroDate            datetime64[ns]
CustomValueEstimate                float64
AlarmImmobiliser                  category
TrackingDevice                    category
CapitalOutstanding                category
NewVehicle                        category
WrittenOff                        category
Rebuilt                           category
Converted                         category
CrossBorder                       category
NumberOfVehiclesInFleet            float64
SumInsured                         float64
TermFrequency                     category
CalculatedPremiumPerTerm           float64
ExcessSelected                    category
CoverCategory                     category
CoverType                         category
CoverGroup                        category
Section                           category
Product                           category
StatutoryClass                    category
StatutoryRiskType                 category
TotalPremium                       float64
TotalClaims                        float64
dtype: object

In [21]:
#To confirm the accuracy of your data types and ensure that each column is correctly interpreted, you can follow these steps:
#Check Unique Values in Categorical Columns
#Verify that categorical columns only contain expected values and are not misinterpreted.
# List of categorical columns
categorical_columns = [
    'Citizenship', 'LegalType', 'Title', 'Language', 'Bank', 'AccountType',
    'MaritalStatus', 'Gender', 'Country', 'Province', 'MainCrestaZone',
    'SubCrestaZone', 'ItemType', 'VehicleType', 'bodytype', 'AlarmImmobiliser',
    'TrackingDevice', 'CapitalOutstanding', 'NewVehicle', 'WrittenOff', 
    'Rebuilt', 'Converted', 'CrossBorder', 'TermFrequency', 'ExcessSelected',
    'CoverCategory', 'CoverType', 'CoverGroup', 'Section', 'Product',
    'StatutoryClass', 'StatutoryRiskType'
]

# Check unique values in categorical columns
for column in categorical_columns:
    print(f"Unique values in '{column}':")
    print(df[column].unique())
    print()

Unique values in 'Citizenship':
['  ', 'AF', 'ZA', 'ZW']
Categories (4, object): ['  ', 'AF', 'ZA', 'ZW']

Unique values in 'LegalType':
['Close Corporation', 'Individual', 'Partnership', 'Private company', 'Public company', 'Sole proprieter']
Categories (6, object): ['Close Corporation', 'Individual', 'Partnership', 'Private company', 'Public company', 'Sole proprieter']

Unique values in 'Title':
['Mr', 'Dr', 'Miss', 'Mrs', 'Ms']
Categories (5, object): ['Dr', 'Miss', 'Mr', 'Mrs', 'Ms']

Unique values in 'Language':
['English']
Categories (1, object): ['English']

Unique values in 'Bank':
['First National Bank', 'Standard Bank', NaN, 'ABSA Bank', 'Capitec Bank', ..., 'Investec Bank', 'Ithala Bank', 'Old Mutual', 'Mercantile Lisbon Bank', 'RMB Private Bank']
Length: 12
Categories (11, object): ['ABSA Bank', 'Capitec Bank', 'First National Bank', 'FirstRand Bank', ..., 'Nedbank', 'Old Mutual', 'RMB Private Bank', 'Standard Bank']

Unique values in 'AccountType':
['Current account', 'Savings account', NaN, 'Transmission account']
Categories (3, object): ['Current account', 'Savings account', 'Transmission account']

Unique values in 'MaritalStatus':
['Not specified', 'Married', 'Single', NaN]
Categories (3, object): ['Married', 'Not specified', 'Single']

Unique values in 'Gender':
['Not specified', 'Male', 'Female', NaN]
Categories (3, object): ['Female', 'Male', 'Not specified']

Unique values in 'Country':
['South Africa']
Categories (1, object): ['South Africa']

Unique values in 'Province':
['Gauteng', 'KwaZulu-Natal', 'Mpumalanga', 'Eastern Cape', 'Western Cape', 'Limpopo', 'North West', 'Free State', 'Northern Cape']
Categories (9, object): ['Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', ..., 'Mpumalanga', 'North West', 'Northern Cape', 'Western Cape']

Unique values in 'MainCrestaZone':
['Rand East', 'Transvaal (all except Pretoria)', 'Johannesburg', 'Natal (Durban)', 'Tembu 2, Cape Mid 2, Cape Mid West, Tembu 1', ..., 'East London', 'Port Elizabeth', 'Ciskei, Cape Mid 1', 'Cape Province', 'Karoo 1 (Northeast of Cape Town)']
Length: 16
Categories (16, object): ['Cape Province', 'Cape Province (Cape Town)', 'Cape Province (East and North of Cape Town)', 'Ciskei, Cape Mid 1', ..., 'Rand East', 'Tembu 2, Cape Mid 2, Cape Mid West, Tembu 1', 'Transvaal (Pretoria)', 'Transvaal (all except Pretoria)']

Unique values in 'SubCrestaZone':
['Rand East', 'Transvaal South', 'Johannesburg', 'Durban', 'Transvaal South East', ..., 'Ciskei', 'OFS North 1 and', 'Coast 2', 'Natal Cape', 'Karoo 2']
Length: 45
Categories (45, object): ['Bloemfontein', 'Bushveld', 'Cape Mid 1', 'Cape Mid 2', ..., 'Transvaal South East', 'Transvaal South West', 'Vaalhartz', 'Zululand']

Unique values in 'ItemType':
['Mobility - Motor']
Categories (1, object): ['Mobility - Motor']

Unique values in 'VehicleType':
['Passenger Vehicle', 'Medium Commercial', 'Heavy Commercial', 'Light Commercial', 'Bus', NaN]
Categories (5, object): ['Bus', 'Heavy Commercial', 'Light Commercial', 'Medium Commercial', 'Passenger Vehicle']

Unique values in 'bodytype':
['S/D', 'SUV', 'MPV', 'H/B', 'P/V', ..., 'D/S', 'S/C', 'C/P', NaN, 'CCL']
Length: 14
Categories (13, object): ['B/S', 'C/C', 'C/P', 'CCL', ..., 'S/C', 'S/D', 'S/W', 'SUV']

Unique values in 'AlarmImmobiliser':
['Yes', 'No']
Categories (2, object): ['No', 'Yes']

Unique values in 'TrackingDevice':
['No', 'Yes']
Categories (2, object): ['No', 'Yes']

Unique values in 'CapitalOutstanding':
['119300', '161000', '52700', '127300', '146800', ..., '184856', '119937', '289418', '174560', '196560']
Length: 660
Categories (659, object): ['-1', '-2', '0', '0.00', ..., '90300', '96300', '98000', '98100']

Unique values in 'NewVehicle':
['More than 6 months', NaN, 'Less than 6 months']
Categories (2, object): ['Less than 6 months', 'More than 6 months']

Unique values in 'WrittenOff':
[NaN, 'No', 'Yes']
Categories (2, object): ['No', 'Yes']

Unique values in 'Rebuilt':
[NaN, 'No', 'Yes']
Categories (2, object): ['No', 'Yes']

Unique values in 'Converted':
[NaN, 'No', 'Yes']
Categories (2, object): ['No', 'Yes']

Unique values in 'CrossBorder':
[NaN, 'No']
Categories (1, object): ['No']

Unique values in 'TermFrequency':
['Monthly', 'Annual']
Categories (2, object): ['Annual', 'Monthly']

Unique values in 'ExcessSelected':
['Mobility - Windscreen', 'Mobility - Metered Taxis - R2000', 'No excess', 'Mobility - Taxi with value more than R100 000..., 'Mobility - Windscreen (Feb2015)', ..., 'Mobility - Metered Taxis - R5000', 'Mobility - R250', 'Mobility - Trailers', 'Mobility - Taxi with value more than R100 000..., 'Mobility - Factory Sound']
Length: 13
Categories (13, object): ['Mobility - Factory Sound', 'Mobility - Metered Taxis - R2000', 'Mobility - Metered Taxis - R5000', 'Mobility - R250', ..., 'Mobility - Trailers', 'Mobility - Windscreen', 'Mobility - Windscreen (Feb2015)', 'No excess']

Unique values in 'CoverCategory':
['Windscreen', 'Own damage', 'Third Party', 'Passenger Liability', 'Signage and Vehicle Wraps', ..., 'Third Party Only', 'Trailer', 'Vehicle over R100 000', 'Vehicle under R100 000', 'Factory Fitted Sound and Other Electronic Equ...]
Length: 28
Categories (28, object): ['Accidental Death', 'Asset Value Preserver', 'Baggage/Luggage', 'Basic Excess Waiver', ..., 'Vehicle over R100 000', 'Vehicle under R100 000', 'Windscreen', 'Windscreen (2015)']

Unique values in 'CoverType':
['Windscreen', 'Own Damage', 'Third Party', 'Passenger Liability', 'Signage and Vehicle Wraps', ..., 'Cash Takings', 'Third Party Only', 'Trailer', 'Fire and Theft', 'Factory Fitted Sound and Other Electronic Equ...]
Length: 22
Categories (22, object): ['Accidental Death', 'Asset Value Preserver', 'Baggage/Luggage', 'Basic Excess Waiver', ..., 'Third Party', 'Third Party Only', 'Trailer', 'Windscreen']

Unique values in 'CoverGroup':
['Comprehensive - Taxi', 'Credit Protection', 'Accidental Death', 'Basic Excess Waiver', 'Income Protector', ..., 'Cash Takings', 'Third Party Only', 'Trailer', 'Fire,Theft and Third Party', 'Motor Comprehensive']
Length: 14
Categories (14, object): ['Accidental Death', 'Asset Value Preserver', 'Baggage/Luggage', 'Basic Excess Waiver', ..., 'Motor Comprehensive', 'Standalone passenger liability', 'Third Party Only', 'Trailer']

Unique values in 'Section':
['Motor Comprehensive', 'Credit Protection', 'Optional Extended Covers', 'Standalone passenger liability', 'Third party or third party, fire and theft only']
Categories (5, object): ['Credit Protection', 'Motor Comprehensive', 'Optional Extended Covers', 'Standalone passenger liability', 'Third party or third party, fire and theft only']

Unique values in 'Product':
['Mobility Metered Taxis: Monthly', 'Mobility Commercial Cover: Monthly', 'Standalone Passenger Liability', 'Bridge Taxi Finance: Monthly']
Categories (4, object): ['Bridge Taxi Finance: Monthly', 'Mobility Commercial Cover: Monthly', 'Mobility Metered Taxis: Monthly', 'Standalone Passenger Liability']

Unique values in 'StatutoryClass':
['Commercial']
Categories (1, object): ['Commercial']

Unique values in 'StatutoryRiskType':
['IFRS Constant']
Categories (1, object): ['IFRS Constant']

In [22]:
df['Citizenship'] = df['Citizenship'].astype('category')

In [23]:
#Citizenship
#Unique Values: [' ', 'AF', 'ZA', 'ZW']
#Issue: The value ' ' (blank spaces) might be a placeholder for missing data or an error. It could be useful to clean or replace this with NaN if it represents missing information.
df['Citizenship'] = df['Citizenship'].replace('  ', pd.NA)

C:\Users\user\AppData\Local\Temp\ipykernel_25592\1056179193.py:4: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df['Citizenship'] = df['Citizenship'].replace('  ', pd.NA)

In [24]:
df['LegalType'] = df['LegalType'].astype('category')

In [25]:
#LegalType
#Current Unique Values: ['Close Corporation', 'Individual', 'Partnership', 'Private company', 'Public company', 'Sole proprieter']
#Action: Correct the spelling error for 'Sole proprieter' to 'Sole proprietor'.
df['LegalType'] = df['LegalType'].replace('Sole proprieter', 'Sole proprietor')

C:\Users\user\AppData\Local\Temp\ipykernel_25592\3130873155.py:4: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df['LegalType'] = df['LegalType'].replace('Sole proprieter', 'Sole proprietor')

In [26]:
# Display unique values in the 'Language' column
df['Language'].unique()

['English']
Categories (1, object): ['English']

In [27]:
# Display value counts for the 'Language' column
df['Language'].value_counts()

Language
English    1000098
Name: count, dtype: int64

In [28]:
df['AccountType'] = df['AccountType'].astype('category')

In [29]:
# Check if 'Unknown' is already in the categories of 'CapitalOutstanding'
if 'Unknown' not in df['CapitalOutstanding'].cat.categories:
    # Add 'Unknown' to the categories
    df['CapitalOutstanding'] = df['CapitalOutstanding'].cat.add_categories('Unknown')

# Now fill NaN values with 'Unknown'
df['CapitalOutstanding'] = df['CapitalOutstanding'].fillna('Unknown')

In [30]:
#MaritalStatus
#Current Unique Values: ['Not specified', 'Married', 'Single', NaN]
#Action: Replace NaN or 'Not specified' with NaN if Not specified is considered missing data.
df['MaritalStatus'] = df['MaritalStatus'].astype('category')
df['MaritalStatus'] = df['MaritalStatus'].replace('Not specified', pd.NA)

C:\Users\user\AppData\Local\Temp\ipykernel_25592\2040687075.py:5: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df['MaritalStatus'] = df['MaritalStatus'].replace('Not specified', pd.NA)

In [31]:
#Gender
#Current Unique Values: ['Not specified', 'Male', 'Female', NaN]
#Action: Replace NaN or 'Not specified' with NaN if Not specified is considered missing data.
df['Gender'] = df['Gender'].astype('category')
df['Gender'] = df['Gender'].replace('Not specified', pd.NA)

C:\Users\user\AppData\Local\Temp\ipykernel_25592\566235291.py:5: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df['Gender'] = df['Gender'].replace('Not specified', pd.NA)

In [32]:
# Check if 'Not specified' is in the categories
if 'Not specified' in df['Gender'].cat.categories:
    # Use .replace_categories() to handle renaming
    df['Gender'] = df['Gender'].cat.rename_categories(
        {'Not specified': pd.NA})

# You can now proceed with any further operations on the 'Gender' column

In [33]:
# Step 1: Add 'Unknown' as a category if it's not already present
if 'Unknown' not in df['VehicleType'].cat.categories:
    df['VehicleType'] = df['VehicleType'].cat.add_categories(['Unknown'])

# Step 2: Now you can fill NaN values with 'Unknown'
df['VehicleType'] = df['VehicleType'].fillna('Unknown')

In [34]:
#bodytype
#Current Unique Values: Multiple body types including NaN.
#Action: Handle NaN values or verify body types.
#df['bodytype'] = df['bodytype'].fillna('Unknown')  # Optional: replace NaN with a placeholder
if 'Unknown' not in df['bodytype'].cat.categories:
    df['bodytype'] = df['bodytype'].cat.add_categories(['Unknown'])

# Step 2: Now you can fill NaN values with 'Unknown'
df['bodytype'] = df['bodytype'].fillna('Unknown')

In [35]:
#CapitalOutstanding
#Current Unique Values: Many values including -1, -2, and 0.00.
#Action: Handle special values like -1 and -2 which might indicate missing or special cases.
# Step 1: Replace commas with empty strings to remove thousand separators
# Step 1: Remove commas (if applicable) and replace non-numeric values with NaN
df['CapitalOutstanding'] = df['CapitalOutstanding'].str.replace(',', '', regex=False)

# Step 2: Replace '-1', '-2', and other non-numeric values like 'Unknown' with NaN
df['CapitalOutstanding'] = df['CapitalOutstanding'].replace(['-1', '-2', 'Unknown'], pd.NA)

# Step 3: Convert the column to float
df['CapitalOutstanding'] = pd.to_numeric(df['CapitalOutstanding'], errors='coerce')

# Now the column should be clean and ready for analysis

In [36]:
#NewVehicle
#Current Unique Values: ['More than 6 months', NaN, 'Less than 6 months']
#Action: Handle NaN values as needed.
# Ensure 'Unknown' is added to the categories
if 'Unknown' not in df['NewVehicle'].cat.categories:
    df['NewVehicle'] = df['NewVehicle'].cat.add_categories(['Unknown'])

# Fill NaN values with 'Unknown'
df['NewVehicle'] = df['NewVehicle'].fillna('Unknown')

In [37]:
#Let's go step by step to apply the suggested cleaning steps, verify the data, and adjust handling for NaN or special values.
# Check for missing values in 'CapitalOutstanding' after conversion
print("CapitalOutstanding - Missing Values: ", df['CapitalOutstanding'].isna().sum())

# Check unique values in 'CapitalOutstanding' to ensure proper cleaning
print("CapitalOutstanding - Unique Values: ", df['CapitalOutstanding'].unique())

# Check for any NaN in 'NewVehicle' column and ensure 'Unknown' has been assigned correctly
print("NewVehicle - Unique Values: ", df['NewVehicle'].unique())
print("NewVehicle - Missing Values: ", df['NewVehicle'].isna().sum())

CapitalOutstanding - Missing Values:  281
CapitalOutstanding - Unique Values:  [1.19300e+05 1.61000e+05 5.27000e+04 1.27300e+05 1.46800e+05 1.40400e+05
 2.08800e+05 8.63000e+04 4.81000e+04 6.24000e+04 0.00000e+00 1.37800e+05
 1.78300e+05 3.94500e+05 2.31300e+05 2.20000e+05 2.40000e+05 2.80000e+05
 2.82100e+05 1.89200e+05 3.64035e+05 3.80000e+05 2.96200e+05 2.50000e+05
 3.20000e+05 3.92000e+05 3.56300e+05 2.52000e+05 3.50000e+05 1.35800e+05
 2.71800e+05 2.32500e+05 3.12000e+05 3.45000e+05 2.41600e+05 2.30000e+05
 2.00000e+05 3.03200e+05 2.70600e+05 3.29500e+05 2.71200e+05 2.75100e+05
 2.48300e+05 2.74400e+05 3.70000e+05 2.45000e+05 2.58800e+05 2.80500e+05
 2.16900e+05 2.43800e+05 1.40000e+05 3.42100e+05 3.49300e+05 2.60900e+05
 2.50300e+05 3.27600e+05 3.32000e+05 2.75000e+05 2.31000e+05 3.87000e+05
 3.43500e+05 2.32700e+05 2.69400e+05 4.27600e+05 3.32800e+05 2.15200e+05
 2.70400e+05 2.75900e+05 3.99500e+05 1.60200e+05 1.76100e+05 2.14600e+05
 2.47700e+05 1.49500e+05 1.98800e+05 2.59200e+05 2.44200e+05 2.96500e+05
 3.39500e+05 3.56301e+05 1.36000e+05 2.94600e+05 3.52800e+05 3.22700e+05
 2.59300e+05 2.64500e+05 1.92400e+05 2.22900e+05 1.15100e+05 1.73400e+05
 4.20000e+05 2.01400e+05 5.09500e+05 2.50700e+05 2.72990e+05 3.25800e+05
 6.00000e+04 2.68900e+05 7.71000e+04 3.40000e+05 2.58200e+05 8.50000e+04
 9.63000e+04 1.31500e+05 1.00000e+05 1.20000e+05 2.65500e+05 2.56900e+05
 3.57300e+05 6.00000e+05 3.00000e+05 3.65000e+05 2.78700e+05 2.18900e+05
 2.73800e+05 3.33000e+05 2.96000e+05 2.01000e+05 2.85900e+05 2.64100e+05
 3.31999e+05 4.00000e+05 1.73800e+05 6.91000e+04 2.59600e+05 3.58700e+05
 1.57000e+05 1.36900e+05 2.02000e+05 2.14000e+05 1.60000e+05 2.84000e+05
 3.93000e+05 1.06000e+05 5.26566e+05 2.97000e+05 2.02800e+05 2.46800e+05
 3.94000e+05 3.75000e+05 3.26200e+05 2.35000e+05 2.70000e+05 2.85000e+05
 3.72500e+05 6.15000e+05 3.61000e+05 2.65000e+05 1.16600e+05 1.33000e+05
 1.38600e+05 3.30500e+05 2.60000e+05 2.48000e+05 2.85700e+05 6.50000e+04
 3.56200e+05 3.60000e+05 1.57600e+05 3.51000e+05 1.38100e+05 1.27900e+05
 2.14100e+05 2.97900e+05 2.81600e+05 3.86649e+05 3.39000e+05 3.56000e+05
 1.72300e+05 3.59000e+05 2.82000e+05 2.51900e+05 3.21000e+05 3.82000e+05
 3.15000e+05 3.90284e+05 3.95000e+05 1.72800e+05 1.97300e+05 4.23282e+05
 2.55300e+05 2.39600e+05 2.33650e+05 3.09650e+05 1.35600e+05 1.62800e+05
 1.98300e+05 1.99990e+05 2.48900e+05 3.39400e+05 2.41197e+05 3.67268e+05
 7.00000e+04 2.41200e+05 1.98000e+05 2.49800e+05 1.44123e+05 2.16800e+05
 1.60400e+05 1.95000e+05 2.04500e+05 2.65400e+05 1.90550e+05 3.22900e+05
 2.84600e+05 3.12100e+05 1.39500e+05 1.59200e+05 2.44600e+05 3.71070e+05
 3.94300e+05 2.79800e+05 2.74000e+05 2.96400e+05 3.54000e+05 3.53700e+05
 2.31100e+05 2.74900e+05 3.46859e+05 1.75000e+05 4.30600e+05 2.97807e+05
 4.97496e+05 2.29900e+05 3.32700e+05 1.13200e+05 1.96300e+05 2.34600e+05
 3.34999e+05 3.47271e+05 2.02100e+05 3.24900e+05 2.15000e+05         nan
 6.54000e+05 1.89989e+05 3.57000e+05 3.35000e+05 3.66000e+05 2.51000e+05
 3.06000e+05 2.24700e+05 2.20200e+05 1.98900e+05 2.58100e+05 4.44500e+05
 1.31912e+05 2.01200e+03 2.42500e+05 2.55200e+05 2.73600e+05 3.18100e+05
 1.90000e+05 2.90000e+05 3.50904e+05 1.45000e+05 7.14330e+04 3.30000e+05
 2.11000e+05 2.72400e+05 2.82200e+05 3.62000e+05 2.64300e+05 2.31887e+05
 2.40600e+05 3.17500e+05 2.39000e+05 1.75200e+05 2.89990e+05 2.47000e+05
 2.99100e+05 6.00200e+05 2.29990e+05 2.34900e+05 2.71100e+05 1.36600e+05
 2.43600e+05 1.43900e+05 2.98990e+05 1.80000e+04 2.50500e+05 2.73700e+05
 1.74600e+05 3.45800e+05 2.28000e+05 3.62300e+05 1.21800e+05 1.62600e+05
 2.77000e+05 1.56100e+05 9.03000e+04 1.37700e+05 1.99400e+05 2.19700e+05
 1.75400e+05 1.76000e+05 1.50000e+05 3.56297e+05 2.62000e+05 3.21500e+05
 4.37634e+05 2.89900e+05 3.84700e+05 3.26300e+05 2.47200e+05 3.03000e+05
 3.37480e+05 2.04700e+05 5.00000e+00 3.43974e+05 1.12300e+05 2.58500e+05
 2.80100e+05 2.72300e+05 4.09400e+05 3.26800e+05 5.59170e+05 2.12500e+05
 2.17700e+05 1.62200e+05 2.55700e+05 3.00700e+05 3.46000e+05 2.76000e+05
 2.81000e+05 3.02000e+05 1.00000e+00 3.17200e+05 2.99990e+05 1.83900e+05
 2.10000e+05 7.65000e+04 3.73148e+05 3.90000e+05 1.78400e+05 2.49500e+05
 1.07570e+05 4.24156e+05 3.31985e+05 5.85950e+05 2.49550e+05 2.47266e+05
 2.35500e+05 4.70000e+05 9.00000e+04 3.37000e+05 3.31073e+05 2.25000e+05
 1.10750e+05 2.37950e+05 2.66100e+05 2.32200e+05 1.83200e+05 2.01600e+05
 1.35000e+05 2.31900e+05 3.60800e+05 3.31600e+05 1.06700e+05 1.80000e+05
 3.28000e+04 3.54272e+05 3.18000e+05 1.84700e+05 2.85700e+07 3.36300e+05
 1.39200e+05 2.67200e+05 1.99900e+05 1.13000e+05 1.14900e+05 3.09900e+05
 2.00300e+05 3.37400e+05 2.03900e+05 2.63000e+05 3.53394e+05 2.66500e+05
 1.20600e+05 3.08000e+05 3.42000e+05 2.63300e+05 1.98400e+05 3.79700e+05
 2.03100e+05 2.52100e+05 2.80900e+05 3.60500e+05 3.42065e+05 5.80000e+05
 2.93300e+05 3.40666e+05 3.56400e+05 3.49700e+05 2.54700e+05 1.59900e+05
 2.18700e+05 2.70200e+05 1.38420e+05 2.15700e+05 2.18000e+05 1.76400e+05
 2.28800e+05 2.51300e+05 2.73000e+05 1.89100e+05 1.94000e+05 2.18200e+05
 2.77500e+05 1.41800e+05 3.97500e+05 6.17000e+05 2.11900e+05 2.17000e+05
 2.26500e+05 3.93700e+05 1.20500e+05 2.47400e+05 2.52300e+05 2.06800e+05
 3.27000e+05 1.61800e+05 1.40900e+05 1.75800e+05 2.69500e+05 3.63500e+05
 1.77900e+05 1.66000e+05 3.10100e+05 1.16300e+05 7.24000e+04 9.80000e+04
 5.27364e+05 2.52500e+05 1.76600e+05 1.77000e+05 2.16700e+05 2.32300e+05
 2.26980e+05 3.39900e+05 3.28900e+05 1.38900e+05 2.50100e+05 1.36700e+05
 6.55000e+04 1.76200e+05 2.45600e+05 2.46000e+05 2.83600e+05 2.54000e+05
 3.12300e+05 3.07000e+05 2.36000e+05 3.50800e+05 4.66000e+05 2.05100e+05
 3.38500e+05 2.57100e+05 4.69339e+05 3.21100e+05 3.63700e+05 9.81000e+04
 5.45000e+05 3.05200e+05 1.30950e+05 1.69300e+05 1.93200e+05 2.33050e+05
 1.91550e+05 3.29100e+05 1.17000e+05 2.12900e+05 3.00000e+04 1.64600e+05
 2.95700e+05 2.16000e+05 2.19200e+05 1.30000e+05 5.40000e+05 5.90000e+05
 2.17200e+05 4.89500e+05 2.58000e+05 2.21700e+05 2.60400e+05 5.00000e+05
 7.14770e+04 1.99040e+05 8.33500e+04 2.18300e+05 2.72000e+05 1.70000e+05
 2.95000e+05 2.04100e+05 4.18000e+05 2.52700e+05 3.55000e+05 2.53300e+05
 3.57420e+05 2.36600e+05 3.83000e+05 3.10000e+05 2.08200e+05 3.00060e+05
 1.46900e+05 3.62650e+05 3.41000e+05 2.69700e+05 3.76600e+05 4.36000e+05
 3.43200e+05 3.36000e+05 1.63000e+05 2.52200e+05 2.46600e+05 3.83909e+05
 2.61700e+05 2.85100e+05 3.36100e+05 3.28600e+05 3.06300e+05 2.93000e+05
 5.09466e+05 3.23000e+05 1.39000e+05 1.58200e+05 2.42800e+05 2.42400e+05
 4.34500e+05 3.56900e+05 1.23100e+05 1.26500e+05 3.56298e+05 3.19019e+05
 3.19700e+05 1.23000e+05 1.78900e+05 4.25890e+05 2.63700e+05 2.87631e+05
 4.10856e+05 4.90000e+05 3.11700e+05 6.30000e+05 2.01100e+03 3.42770e+05
 1.99800e+05 3.27114e+05 3.45328e+05 3.34000e+05 3.56029e+05 3.68000e+05
 2.81300e+05 2.29950e+05 4.34530e+05 1.38000e+05 3.59300e+05 2.34990e+05
 1.33500e+05 1.58300e+05 2.94800e+05 3.09800e+05 6.70000e+05 2.96800e+05
 3.74300e+05 3.67600e+05 3.36900e+05 5.15000e+05 2.26200e+05 2.93299e+05
 3.49800e+05 2.16200e+05 3.63000e+05 2.28500e+05 2.57550e+05 3.45300e+05
 2.66400e+05 5.02000e+05 7.90000e+04 5.50000e+05 1.92600e+05 2.49700e+05
 2.82800e+05 1.85000e+05 4.70498e+05 1.41900e+05 1.69494e+05 2.63306e+05
 4.24000e+05 2.41300e+05 2.33700e+05 2.41350e+05 2.09800e+05 2.30600e+05
 1.25000e+05 2.27375e+05 2.49000e+05 7.00000e+05 3.75980e+05 2.13700e+05
 3.49900e+05 1.54900e+05 2.29000e+05 3.52650e+05 3.58600e+05 3.57151e+05
 1.33100e+05 2.46200e+05 2.93900e+05 2.80000e+07 1.88690e+05 3.18339e+05
 2.16999e+05 3.29250e+05 4.25500e+05 3.49100e+05 1.29000e+05 3.27233e+05
 4.90000e+04 1.83000e+05 2.69900e+05 2.00000e+04 2.13600e+05 1.97810e+05
 3.39333e+05 3.12900e+05 1.37000e+04 3.50000e+04 1.26000e+05 1.19937e+05
 1.37500e+05 1.52000e+05 1.59000e+05 1.69000e+05 1.55000e+05 1.65000e+05
 1.49600e+05 1.54584e+05 1.58000e+05 1.61346e+05 1.74000e+05 1.80100e+05
 1.81512e+05 1.89000e+05 1.84000e+05 1.84500e+05 1.39106e+05 1.53000e+05
 1.78512e+05 2.90825e+05 1.87775e+05 1.84856e+05 2.89418e+05 1.74560e+05
 1.96560e+05]
NewVehicle - Unique Values:  ['More than 6 months', 'Unknown', 'Less than 6 months']
Categories (3, object): ['Less than 6 months', 'More than 6 months', 'Unknown']
NewVehicle - Missing Values:  0

In [59]:
# Validate the cleaning process
print("Check how many NaN values are left")
print(df.isna().sum())  # Check how many NaN values are left
print("Check unique values for 'Citizenship'")
print(df['Citizenship'].unique())  # Check unique values for 'Citizenship'
print("Check summary stats for 'CapitalOutstanding'")
print(df['CapitalOutstanding'].describe())  # Check summary stats for 'CapitalOutstanding'

Check how many NaN values are left
UnderwrittenCoverID               0
PolicyID                          0
TransactionMonth                  0
IsVATRegistered                   0
Citizenship                       0
LegalType                         0
Title                             0
Language                          0
Bank                         145961
AccountType                   40232
MaritalStatus                  8259
Gender                         9536
Country                           0
Province                          0
PostalCode                        0
MainCrestaZone                    0
SubCrestaZone                     0
ItemType                          0
mmcode                          552
VehicleType                     552
RegistrationYear                  0
make                            552
Model                           552
Cylinders                       552
cubiccapacity                   552
kilowatts                       552
bodytype                        552
NumberOfDoors                   552
VehicleIntroDate                552
CustomValueEstimate          779642
AlarmImmobiliser                  0
TrackingDevice                    0
CapitalOutstanding                2
NewVehicle                   153295
WrittenOff                   641901
Rebuilt                      641901
Converted                    641901
CrossBorder                  999400
NumberOfVehiclesInFleet     1000098
SumInsured                        0
TermFrequency                     0
CalculatedPremiumPerTerm          0
ExcessSelected                    0
CoverCategory                     0
CoverType                         0
CoverGroup                        0
Section                           0
Product                           0
StatutoryClass                    0
StatutoryRiskType                 0
TotalPremium                      0
TotalClaims                       0
dtype: int64
Check unique values for 'Citizenship'
['  ' 'AF' 'ZA' 'ZW']
Check summary stats for 'CapitalOutstanding'
count     1000096
unique        659
top             0
freq       779482
Name: CapitalOutstanding, dtype: object

In [60]:
# Drop 'CrossBorder' and 'NumberOfVehiclesInFleet' if they are irrelevant
df = df.drop(['CrossBorder', 'NumberOfVehiclesInFleet'], axis=1)

# Impute missing values for 'MaritalStatus' and 'Gender' with 'Unknown'
df['MaritalStatus'] = df['MaritalStatus'].fillna('Unknown')
df['Gender'] = df['Gender'].fillna('Unknown')

# Impute missing 'CustomValueEstimate' with the median
df['CustomValueEstimate'] = df['CustomValueEstimate'].fillna(df['CustomValueEstimate'].median())

# Drop rows where 'CapitalOutstanding' is NaN (only 281 missing)
df = df.dropna(subset=['CapitalOutstanding'])

# For 'WrittenOff', 'Rebuilt', 'Converted' impute missing with 'No' assuming missing means 'No'
df['WrittenOff'] = df['WrittenOff'].fillna('No')
df['Rebuilt'] = df['Rebuilt'].fillna('No')
df['Converted'] = df['Converted'].fillna('No')

In [61]:
#Verification of Column Values
print(df['Citizenship'].dtype)

object

In [62]:
if df['Citizenship'].dtype.name == 'category':
    # Add the new category if it doesn't exist
    if 'Unknown' not in df['Citizenship'].cat.categories:
        df['Citizenship'] = df['Citizenship'].cat.add_categories(['Unknown'])

    # Now fill NaN values
    df['Citizenship'] = df['Citizenship'].fillna('Unknown')
else:
    # If it's not categorical, you can directly fill NaN values
    df['Citizenship'] = df['Citizenship'].fillna('Unknown')

In [64]:
# Check for remaining NaN values in the DataFrame
nan_summary = df.isna().sum()
print("Remaining NaN values in each column:\n", nan_summary)

Remaining NaN values in each column:
 UnderwrittenCoverID              0
PolicyID                         0
TransactionMonth                 0
IsVATRegistered                  0
Citizenship                      0
LegalType                        0
Title                            0
Language                         0
Bank                        145959
AccountType                  40230
MaritalStatus                    0
Gender                           0
Country                          0
Province                         0
PostalCode                       0
MainCrestaZone                   0
SubCrestaZone                    0
ItemType                         0
mmcode                         552
VehicleType                    552
RegistrationYear                 0
make                           552
Model                          552
Cylinders                      552
cubiccapacity                  552
kilowatts                      552
bodytype                       552
NumberOfDoors                  552
VehicleIntroDate               552
CustomValueEstimate              0
AlarmImmobiliser                 0
TrackingDevice                   0
CapitalOutstanding               0
NewVehicle                  153295
WrittenOff                       0
Rebuilt                          0
Converted                        0
SumInsured                       0
TermFrequency                    0
CalculatedPremiumPerTerm         0
ExcessSelected                   0
CoverCategory                    0
CoverType                        0
CoverGroup                       0
Section                          0
Product                          0
StatutoryClass                   0
StatutoryRiskType                0
TotalPremium                     0
TotalClaims                      0
dtype: int64

In [65]:
# Example of filling NaN values with placeholders or statistics
df['mmcode'] = df['mmcode'].fillna('Unknown')  # Placeholder for categorical data
df['make'] = df['make'].fillna('Unknown')  # Placeholder for categorical data
df['Model'] = df['Model'].fillna('Unknown')  # Placeholder for categorical data
df['Cylinders'] = df['Cylinders'].fillna(df['Cylinders'].median())  # Median for numerical data
df['cubiccapacity'] = df['cubiccapacity'].fillna(df['cubiccapacity'].median())  # Median for numerical data
df['kilowatts'] = df['kilowatts'].fillna(df['kilowatts'].median())  # Median for numerical data
df['NumberOfDoors'] = df['NumberOfDoors'].fillna(df['NumberOfDoors'].mode()[0])  # Mode for categorical data
df['VehicleIntroDate'] = df['VehicleIntroDate'].fillna('Unknown')  # Placeholder for date or categorical data

In [66]:
# Convert categorical column to object type
df['make'] = df['make'].astype(str)

# Fill NaN values
df['make'] = df['make'].fillna('Unknown')

# Convert back to categorical if needed
df['make'] = df['make'].astype('category')

In [68]:
# Ensure columns are numeric
df['Cylinders'] = pd.to_numeric(df['Cylinders'], errors='coerce')
df['cubiccapacity'] = pd.to_numeric(df['cubiccapacity'], errors='coerce')
df['kilowatts'] = pd.to_numeric(df['kilowatts'], errors='coerce')

# Fill NaN values with median
df['Cylinders'] = df['Cylinders'].fillna(df['Cylinders'].median())
df['cubiccapacity'] = df['cubiccapacity'].fillna(df['cubiccapacity'].median())
df['kilowatts'] = df['kilowatts'].fillna(df['kilowatts'].median())

In [69]:
# Check remaining NaNs
print(df.isna().sum())

UnderwrittenCoverID              0
PolicyID                         0
TransactionMonth                 0
IsVATRegistered                  0
Citizenship                      0
LegalType                        0
Title                            0
Language                         0
Bank                        145959
AccountType                  40230
MaritalStatus                    0
Gender                           0
Country                          0
Province                         0
PostalCode                       0
MainCrestaZone                   0
SubCrestaZone                    0
ItemType                         0
mmcode                           0
VehicleType                    552
RegistrationYear                 0
make                             0
Model                            0
Cylinders                        0
cubiccapacity                    0
kilowatts                        0
bodytype                       552
NumberOfDoors                    0
VehicleIntroDate                 0
CustomValueEstimate              0
AlarmImmobiliser                 0
TrackingDevice                   0
CapitalOutstanding               0
NewVehicle                  153295
WrittenOff                       0
Rebuilt                          0
Converted                        0
SumInsured                       0
TermFrequency                    0
CalculatedPremiumPerTerm         0
ExcessSelected                   0
CoverCategory                    0
CoverType                        0
CoverGroup                       0
Section                          0
Product                          0
StatutoryClass                   0
StatutoryRiskType                0
TotalPremium                     0
TotalClaims                      0
dtype: int64

In [70]:
# Convert to categorical if not already
if not isinstance(df['Model'].dtype, pd.CategoricalDtype):
    df['Model'] = df['Model'].astype('category')

# Add 'Unknown' to categories
categories = df['Model'].cat.categories.tolist()  # Get existing categories
if 'Unknown' not in categories:
    categories.append('Unknown')
    df['Model'] = df['Model'].cat.set_categories(categories)  # Update categories

# Fill NaN values
df['Model'] = df['Model'].fillna('Unknown')

In [71]:
# Handling numerical columns
df['NumberOfDoors'] = df['NumberOfDoors'].fillna(df['NumberOfDoors'].mode()[0])

# Handling date or object columns
df['VehicleIntroDate'] = df['VehicleIntroDate'].fillna('Unknown')

In [50]:
# Verify remaining NaN values
print("Remaining NaN values:\n", df.isna().sum())

# Check data types
print("Data types of columns:\n", df.dtypes)

# Save to CSV file
df.to_csv('cleaned_data.csv', index=False)

Remaining NaN values:
 UnderwrittenCoverID               0
PolicyID                          0
TransactionMonth                  0
IsVATRegistered                   0
Citizenship                       0
LegalType                         0
Title                             0
Language                          0
Bank                         145961
AccountType                   40232
MaritalStatus                994467
Gender                       950526
Country                           0
Province                          0
PostalCode                        0
MainCrestaZone                    0
SubCrestaZone                     0
ItemType                          0
mmcode                            0
VehicleType                       0
RegistrationYear                  0
make                              0
Model                             0
Cylinders                         0
cubiccapacity                     0
kilowatts                         0
bodytype                          0
NumberOfDoors                     0
VehicleIntroDate                  0
CustomValueEstimate          779642
AlarmImmobiliser                  0
TrackingDevice                    0
CapitalOutstanding              281
NewVehicle                        0
WrittenOff                   641901
Rebuilt                      641901
Converted                    641901
CrossBorder                  999400
NumberOfVehiclesInFleet     1000098
SumInsured                        0
TermFrequency                     0
CalculatedPremiumPerTerm          0
ExcessSelected                    0
CoverCategory                     0
CoverType                         0
CoverGroup                        0
Section                           0
Product                           0
StatutoryClass                    0
StatutoryRiskType                 0
TotalPremium                      0
TotalClaims                       0
dtype: int64
Data types of columns:
 UnderwrittenCoverID                  int64
PolicyID                             int64
TransactionMonth            datetime64[ns]
IsVATRegistered                       bool
Citizenship                       category
LegalType                         category
Title                             category
Language                          category
Bank                              category
AccountType                       category
MaritalStatus                     category
Gender                            category
Country                           category
Province                          category
PostalCode                           int64
MainCrestaZone                    category
SubCrestaZone                     category
ItemType                          category
mmcode                              object
VehicleType                       category
RegistrationYear                     int64
make                              category
Model                             category
Cylinders                          float64
cubiccapacity                      float64
kilowatts                          float64
bodytype                          category
NumberOfDoors                      float64
VehicleIntroDate                    object
CustomValueEstimate                float64
AlarmImmobiliser                  category
TrackingDevice                    category
CapitalOutstanding                 float64
NewVehicle                        category
WrittenOff                        category
Rebuilt                           category
Converted                         category
CrossBorder                       category
NumberOfVehiclesInFleet            float64
SumInsured                         float64
TermFrequency                     category
CalculatedPremiumPerTerm           float64
ExcessSelected                    category
CoverCategory                     category
CoverType                         category
CoverGroup                        category
Section                           category
Product                           category
StatutoryClass                    category
StatutoryRiskType                 category
TotalPremium                       float64
TotalClaims                        float64
dtype: object

322

In [53]:
import pandas as pd
from sqlalchemy import create_engine

# Database connection configuration
db_config = {
    'host': 'localhost',
    'port': '5432',
    'dbname': 'week3',
    'user': 'postgres',
    'password': '123456'
}

# Create engine
engine = create_engine(f"postgresql://{db_config['user']}:{db_config['password']}@{db_config['host']}:{db_config['port']}/{db_config['dbname']}")

# Query data
query = "SELECT * FROM week_3_data;"
df = pd.read_sql(query, engine)

# Perform analysis on the DataFrame
print(df.head())

   UnderwrittenCoverID  PolicyID TransactionMonth  IsVATRegistered  \
0               145249     12827       2015-03-01             True
1               145249     12827       2015-05-01             True
2               145249     12827       2015-07-01             True
3               145255     12827       2015-05-01             True
4               145255     12827       2015-07-01             True

  Citizenship          LegalType Title Language                 Bank  \
0     Unknown  Close Corporation    Mr  English  First National Bank
1     Unknown  Close Corporation    Mr  English  First National Bank
2     Unknown  Close Corporation    Mr  English  First National Bank
3     Unknown  Close Corporation    Mr  English  First National Bank
4     Unknown  Close Corporation    Mr  English  First National Bank

       AccountType  ...                    ExcessSelected CoverCategory  \
0  Current account  ...             Mobility - Windscreen    Windscreen
1  Current account  ...             Mobility - Windscreen    Windscreen
2  Current account  ...             Mobility - Windscreen    Windscreen
3  Current account  ...  Mobility - Metered Taxis - R2000    Own damage
4  Current account  ...  Mobility - Metered Taxis - R2000    Own damage

    CoverType            CoverGroup              Section  \
0  Windscreen  Comprehensive - Taxi  Motor Comprehensive
1  Windscreen  Comprehensive - Taxi  Motor Comprehensive
2  Windscreen  Comprehensive - Taxi  Motor Comprehensive
3  Own Damage  Comprehensive - Taxi  Motor Comprehensive
4  Own Damage  Comprehensive - Taxi  Motor Comprehensive

                           Product StatutoryClass StatutoryRiskType  \
0  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
1  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
2  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
3  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
4  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant

  TotalPremium TotalClaims
0    21.929825         0.0
1    21.929825         0.0
2     0.000000         0.0
3   512.848070         0.0
4     0.000000         0.0

[5 rows x 52 columns]